# Generated by Django 3.1.7 on 2021-04-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mst_dev_conn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.UUIDField()),
                ('ipAddress', models.CharField(max_length=20)),
                ('portNumber', models.IntegerField()),
                ('plcName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shift_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.UUIDField()),
                ('StartShiftTime', models.TimeField()),
                ('EndShiftTime', models.TimeField()),
                ('ShiftNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='units_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_id', models.UUIDField()),
                ('unitConversionFactor', models.FloatField()),
                ('unitName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level_id', models.UUIDField()),
                ('LevelName', models.CharField(max_length=30)),
                ('LevelNamePriority', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_mng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('Username', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=10)),
                ('user_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.user_level')),
            ],
        ),
        migrations.CreateModel(
            name='mst_dev_addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_addr_id', models.UUIDField()),
                ('holdingRegisterNumber', models.IntegerField()),
                ('ReadRegisterCount', models.SmallIntegerField()),
                ('registerType', models.CharField(max_length=10)),
                ('deviceName', models.CharField(max_length=50)),
                ('dev_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DevConnection', to='bknd_iDAQ.mst_dev_conn')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.units_table')),
            ],
        ),
        migrations.CreateModel(
            name='mst_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_id', models.UUIDField()),
                ('DataValue', models.FloatField()),
                ('AlarmStatus', models.BooleanField()),
                ('DateTime', models.DateTimeField()),
                ('dev_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.mst_dev_addr')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.shift_table')),
            ],
        ),
    ]
