# Generated by Django 3.1.7 on 2021-04-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_iDAQ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mst_dev_addr',
            name='dev_id',
        ),
        migrations.RemoveField(
            model_name='mst_dev_addr',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='user_mng',
            name='user_level_id',
        ),
        migrations.RemoveField(
            model_name='mst_dev_conn',
            name='dev_id',
        ),
        migrations.RemoveField(
            model_name='shift_table',
            name='shift_id',
        ),
        migrations.RemoveField(
            model_name='units_table',
            name='Unit_id',
        ),
        migrations.RemoveField(
            model_name='user_level',
            name='user_level_id',
        ),
        migrations.DeleteModel(
            name='mst_data',
        ),
        migrations.DeleteModel(
            name='mst_dev_addr',
        ),
        migrations.DeleteModel(
            name='user_mng',
        ),
    ]
