# Generated by Django 3.1.7 on 2021-04-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_iDAQ', '0002_auto_20210408_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='mst_dev_addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdingRegisterNumber', models.IntegerField()),
                ('ReadRegisterCount', models.SmallIntegerField()),
                ('registerType', models.CharField(max_length=10)),
                ('deviceName', models.CharField(max_length=50)),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.mst_dev_conn')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.units_table')),
            ],
        ),
    ]
