# Generated by Django 3.1.7 on 2021-04-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_iDAQ', '0003_mst_dev_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mst_dev_addr',
            old_name='id1',
            new_name='mst_dev_conn_id',
        ),
        migrations.RenameField(
            model_name='mst_dev_addr',
            old_name='id2',
            new_name='units_table_id',
        ),
        migrations.CreateModel(
            name='user_mng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('PassWord', models.CharField(max_length=10)),
                ('user_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.user_level')),
            ],
        ),
        migrations.CreateModel(
            name='mst_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataValue', models.FloatField()),
                ('AlarmStatus', models.BooleanField()),
                ('DateTime', models.DateTimeField()),
                ('mst_dev_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.mst_dev_addr')),
                ('shift_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bknd_iDAQ.shift_table')),
            ],
        ),
    ]
