# Generated by Django 2.0.2 on 2021-04-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_iDAQ', '0004_auto_20210408_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mst_dev_conn',
            old_name='plcName',
            new_name='deviceName',
        ),
    ]
