# Generated by Django 2.0.2 on 2021-03-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlcAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plcDataAddrID', models.UUIDField()),
                ('holdingRegisterNumber', models.IntegerField()),
                ('ReadRegisterCount', models.SmallIntegerField()),
                ('registerType', models.CharField(max_length=10)),
                ('deviceName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlcTcpConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plcID', models.UUIDField()),
                ('ipAddress', models.CharField(max_length=20)),
                ('portNumber', models.IntegerField()),
                ('plcName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID', models.UUIDField()),
                ('unitName', models.CharField(max_length=20)),
                ('unitConversionFactor', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='plcaddress',
            name='plcID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendIDAQ_rest.PlcTcpConnection'),
        ),
    ]
