# Generated by Django 3.1.7 on 2021-03-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendIDAQ_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShiftID', models.UUIDField()),
                ('StartShiftTime', models.TimeField()),
                ('EndShiftTime', models.TimeField()),
                ('ShiftNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataID', models.UUIDField()),
                ('DataValue', models.FloatField()),
                ('AlarmStatus', models.BooleanField()),
                ('DateTime', models.DateTimeField()),
                ('ShiftID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendIDAQ_rest.shifttable')),
                ('plcDataAddrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendIDAQ_rest.plcaddress')),
            ],
        ),
    ]
