# Generated by Django 3.1.7 on 2021-03-22 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendIDAQ_rest', '0003_userlevel_usermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcaddress',
            name='unitID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendIDAQ_rest.unittable'),
        ),
    ]
