# Generated by Django 3.1.7 on 2021-03-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendIDAQ_rest', '0005_auto_20210322_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='DataID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plcaddress',
            name='plcDataAddrID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plctcpconnection',
            name='plcID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shifttable',
            name='ShiftID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unittable',
            name='unitID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='UserLevelID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='UserID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
